- name: Ensure Helm is installed
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Create monitoring namespace
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: monitoring
    state: present

- name: Add Helm repo - prometheus-community
  community.kubernetes.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Add Helm repo - grafana
  community.kubernetes.helm_repository:
    name: grafana
    repo_url: https://grafana.github.io/helm-charts

- name: Install Prometheus
  community.kubernetes.helm:
    name: prometheus
    chart_ref: prometheus-community/prometheus
    release_namespace: monitoring
    values:
      server:
        service:
          type: NodePort

- name: Install Grafana
  community.kubernetes.helm:
    name: grafana
    chart_ref: grafana/grafana
    release_namespace: monitoring
    values:
      service:
        type: NodePort
      adminPassword: admin
      persistence:
        enabled: true