apiVersion: v1
kind: Pod
metadata:
  name: go-webapp-pod
  labels:
    app: gowebapp
    type: backend
spec:
  containers:
  - name: go-webapp-container
    image: ybkuroki/go-webapp-sample:1.5.1
    ports:
    - containerPort: 8080