pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'docker build -t ipp-app:latest .'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh './scripts/deploy.sh'
            }
        }
    }
}