pipeline {
    agent any
    stages {
        
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'SubmoduleOption',
                            recursiveSubmodules: true,
                            trackingSubmodules: true,
                            reference: '',
                            timeout: 10
                        ]
                    ],
                    userRemoteConfigs: [[
                        url: 'https://github.com/RuParada/ipp_infrastructure.git'
                    ]]
                ])
            }
        }
        stage('Install dependencies') {
            steps {
                dir('ipp') {
                    sh 'yarn install --frozen-lockfile'
                }
            }
        }
        stage('Build Docker image') {
            steps {
                dir('ipp_infrastructure') {
                    sh 'docker build -t ipp-app:latest .'
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                dir('ipp_infrastructure') {
                    sh 'chmod +x scripts/deploy.sh'
                    sh './scripts/deploy.sh'
                }
            }
        }
    }
}