pipeline {
    agent any
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [
                        [$class: 'SubmoduleOption',
                            recursiveSubmodules: true,
                            trackingSubmodules: true,
                            reference: '',
                            timeout: 10
                        ]
                    ],
                    userRemoteConfigs: [[
                        url: 'https://github.com/RuParada/ipp_infrastructure.git'
                    ]]
                ])
            }
        }
        stage('Build') {
            steps {
                sh 'docker build -t ipp-app:latest .'
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                sh './scripts/deploy.sh'
            }
        }
    }
}